# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.1.dev5+g80ff7d0.d20230803'
__version_tuple__ = version_tuple = (0, 4, 1, 'dev5', 'g80ff7d0.d20230803')
